import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import Layout from './components/Layout/Layout';
import './globals.css';

const manropeSans = Manrope({
	variable: '--font-manrope-sans',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Excellent Care Clinic Planner',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<body className={`${manropeSans.variable} antialiased`}>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
